# docker-compose.yml 

## Simple docker compose for current Dockerfile. 
## Expose port 1337 

## Doc 
## https://docs.strapi.io/dev-docs/installation/docker

version: '3.9'

services:
  app:
    container_name: strapi
    build: .
    command: bash -c "yarn install && yarn develop"
    
    # image: strapi:latest
    restart: unless-stopped
    env_file: .env
    environment:
      - NODE_ENV=development
      - PORT=1337
    ports:
      - "1337:1337"
    volumes:
      - .:/opt/app
